language: node_js

node_js:
    - '12'
    - '10'

# everything below is Code Climate setup based on
# https://github.com/codeclimate/test-reporter/blob/master/examples/javascript_examples.md

before_script:
    - yarn global add nyc
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - nyc --reporter=lcov yarn run test

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
