language: node_js

node_js:
    - '12'
    - '10'

# everything below is Code Climate setup based on
# https://docs.codeclimate.com/docs/travis-ci-test-coverage#section-travis-ci-single-test-suite-non-parallel-builds

env:
    global:
        - CC_TEST_REPORTER_ID=cf4776fed825e915f4c0fb98737a5920c854ad5d5554ddb8d347e955b60f4b6f

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - bundle exec rspec

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
