name: CI
on:
    - push
    - pull_request
jobs:
    test:
        name: Node.js ${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            # `fail-fast` is set to `false` because we won't know which Node versions are failing and which are passing
            fail-fast: false
            matrix:
                node-version:
                    - 18
                    - 16
                    - 14
                    - 12
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn install
            - run: yarn test
    coverage:
        needs: [test]
        name: coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: 16
            - run: yarn install
            - uses: paambaati/codeclimate-action@v2.2.4
              env:
                  CC_TEST_REPORTER_ID: cf4776fed825e915f4c0fb98737a5920c854ad5d5554ddb8d347e955b60f4b6f
              with:
                  coverageCommand: yarn test
